### ISSUE TITLE
你好，我按照这个操作了，但是还是不能打电话，请问你认为可能是什么原因，谢谢了

### ISSUE THREAD

**Issue by baolfire** [Magisk-Modules-Repo/Xiaomi-Mi-A1-gsm-fixes#1]
你好，我按照这个操作了，只有一次在los上成功了，双清刷了los + gapps后又不行了，在官方rom上也不行，请问你认为可能是什么原因或者还需要进行什么操作，谢谢了

**Comment by wonderil** [comment]
When you upgrade to the official Version: V9.6.4.0.ODHMIFE (Android O), the
secondary method has expired. This plugin has been submitted for removal. I
have changed my phone and I don't guarantee availability.

baolfire <notifications@github.com> 于2018年7月30日周一 下午10:23写道：
